# Ubuntu 12.04
language: generic
env:
  matrix:
    - EMACS=emacs24             # This is 24.3
    - EMACS=emacs-snapshot

before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo add-apt-repository -y ppa:ubuntu-elisp
  - sudo apt-get update -qq
  - sudo apt-get install -qq $EMACS

script:
  - $EMACS --version
  - make EMACSBIN=$EMACS
